name: a3_udwmj
description: "Avaliação A3"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.1

dependencies:
  device_preview: ^1.2.0
  flutter:
    sdk: flutter
  http: ^1.2.2
  path: ^1.9.0
  sqflite: ^2.4.0
  sqflite_common_ffi: any
  flutter_native_splash: ^2.0.0
  flutter_launcher_icons: ^0.14.1
  provider: ^6.0.5
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/Taskify.png
    - assets/Estudante1.png
    - assets/Calendario.png
    - assets/Dashboard.png
    - assets/Perfil.png
    - assets/Settings.png        